### ISSUE TITLE
f32 roll-out fiasco retrospective

### ISSUE THREAD

**Issue by isimluk** [RedHatGov/ocdb#29]
The application builds on `fedora:latest`. When `:latest` switched from f31 to f32 we application wouldn't boot in openshift presenting us with the bellow traceback. Interestingly, application continued to work well in local (non-openshift, f32) environment.

Situation was resolved by rebuilding container on top of f31.

Potential action items:
 * introduce `/api/healthcheck` http end point to stop automatic openshift roll-out in cases when application is not in good shape
 * migrate to rhel8 image instead of fedora:latest

Kudos go to @redhatrises for spotting the f31/f32 mismatch immediately.

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f819419188b]

runtime stack:
runtime.throw(0x1016175, 0x2a)
        /usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xbdf070, 0xc0001e5ae8, 0xc0002e40b8)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc0001e5ab8 sp=0xc0001e5a80 pc=0x4054ab
os/user._Cfunc_mygetpwuid_r(0x3c40a6f0, 0xc0002d7ef0, 0x5b52d00, 0x400, 0xc0002e40b8, 0xc000000000)
        _cgo_gotypes.go:173 +0x4d fp=0xc0001e5ae8 sp=0xc0001e5ab8 pc=0x9548cd
os/user.lookupUnixUid.func1.1(0x3c40a6f0, 0xc0002d7ef0, 0xc0002df0b0, 0xc0002e40b8, 0xc0001e5b88)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:103 +0x14c fp=0xc0001e5b38 sp=0xc0001e5ae8 pc=0x955e0c
os/user.lookupUnixUid.func1(0xf2a3c0)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:103 +0x45 fp=0xc0001e5b70 sp=0xc0001e5b38 pc=0x955ea5
os/user.retryWithBuffer(0xc0002df0b0, 0xc0001e5c80, 0x479eec, 0x4475460)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:251 +0x3b fp=0xc0001e5bc8 sp=0xc0001e5b70 pc=0x95538b
os/user.lookupUnixUid(0x3c40a6f0, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:96 +0x14c fp=0xc0001e5cb8 sp=0xc0001e5bc8 pc=0x954d0c
os/user.current(0x42f20a, 0xe, 0x1)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:49 +0x49 fp=0xc0001e5cf8 sp=0xc0001e5cb8 pc=0x954b89
os/user.Current.func1()
        /usr/local/go/src/os/user/lookup.go:15 +0x22 fp=0xc0001e5d20 sp=0xc0001e5cf8 pc=0x955c42
sync.(*Once).doSlow(0x44ed860, 0x2334188)
        /usr/local/go/src/sync/once.go:66 +0xe3 fp=0xc0001e5dc0 sp=0xc0001e5d20 pc=0x479e33
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:57
os/user.Current(0xe, 0x1, 0xc00003c009)
        /usr/local/go/src/os/user/lookup.go:15 +0xf2 fp=0xc0001e5df0 sp=0xc0001e5dc0 pc=0x9545f2
github.com/gobuffalo/buffalo/plugins.glob..func1(0x0, 0xc0001e5e90)
        /go/pkg/mod/github.com/gobuffalo/buffalo@v0.16.8/plugins/cache.go:26 +0x26 fp=0xc0001e5e58 sp=0xc0001e5df0 pc=0xae8e86
github.com/gobuffalo/buffalo/plugins.init()
        /go/pkg/mod/github.com/gobuffalo/buffalo@v0.16.8/plugins/cache.go:30 +0x26 fp=0xc0001e5ea0 sp=0xc0001e5e58 pc=0xaea116
runtime.doInit(0x4495440)
        /usr/local/go/src/runtime/proc.go:5222 +0x8a fp=0xc0001e5ed0 sp=0xc0001e5ea0 pc=0x43e15a
runtime.doInit(0x4499920)
        /usr/local/go/src/runtime/proc.go:5217 +0x57 fp=0xc0001e5f00 sp=0xc0001e5ed0 pc=0x43e127
runtime.doInit(0x44945c0)
        /usr/local/go/src/runtime/proc.go:5217 +0x57 fp=0xc0001e5f30 sp=0xc0001e5f00 pc=0x43e127
runtime.doInit(0x4493720)
        /usr/local/go/src/runtime/proc.go:5217 +0x57 fp=0xc0001e5f60 sp=0xc0001e5f30 pc=0x43e127
runtime.main()
        /usr/local/go/src/runtime/proc.go:190 +0x1da fp=0xc0001e5fe0 sp=0xc0001e5f60 pc=0x431dba
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0001e5fe8 sp=0xc0001e5fe0 pc=0x45d8a1
```

**Comment by isimluk** [comment]
We cannot easily migrate towards ubi since public Quay instance is not registered through subscription manager.
```
dnf install -y bash git ca-certificates cmake make openscap-scanner python3-pyyaml python3-jinja2 && dnf clean all
7/10/2020, 8:06:20 PM
7/10/2020, 8:06:20 PM ---> Running in 55e61a68d239
7/10/2020, 8:06:21 PM Updating Subscription Management repositories.
7/10/2020, 8:06:21 PM Unable to read consumer identity
7/10/2020, 8:06:21 PM This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
7/10/2020, 8:06:21 PM Red Hat Universal Base Image 8 (RPMs) - BaseOS 8.2 MB/s | 766 kB 00:00
7/10/2020, 8:06:21 PM Red Hat Universal Base Image 8 (RPMs) - AppStre 41 MB/s | 3.9 MB 00:00
7/10/2020, 8:06:22 PM Red Hat Universal Base Image 8 (RPMs) - CodeRea 149 kB/s | 11 kB 00:00
7/10/2020, 8:06:22 PM Package bash-4.4.19-10.el8.x86_64 is already installed.
7/10/2020, 8:06:22 PM Package ca-certificates-2019.2.32-80.0.el8_1.noarch is already installed.
7/10/2020, 8:06:22 PM No match for argument: openscap-scanner
7/10/2020, 8:06:22 PM No match for argument: python3-pyyaml
7/10/2020, 8:06:22 PM Error: Unable to find a match: openscap-scanner python3-pyyaml 
```

**Comment by isimluk** [comment]
Readiness probe is sst-up and deployed.

**Comment by isimluk** [comment]
Actually, we will have to roll-back readiness probe.

The readiness probe is configured to be HTTP, but openshift after the latest upgrade started to send HTTPS requests.

Previously:

```
INFO[2020-07-27T21:16:14Z] /api/v1/admin/readiness/ duration="341.602µs" human_size="21 B" method=GET params="{}" path=/api/v1/admin/readiness/ render="61.256µs" request_id=5926ec87aec4ace444db-7dc7fde9d74cd63478d6 size=21 status=200
```

Now:
```
level=info time="2020-07-27T21:14:53Z" msg="https://10.130.29.150:3000/api/v1/admin/readiness/ " duration="50.367µs" human_size="85 B" method=GET path="https://10.130.29.150:3000/api/v1/admin/readiness/ " request_id=9aab58cf2900112d8af7-ef30d221ac51eeace18d size=85 status=301
```

While we haven't changed anything in a past 5 or so days.

@redhatrises, FYI

**Comment by redhatrises** [comment]
@isimluk could this also be because we are now doing https through let's encrypt?

**Comment by isimluk** [comment]
Not sure, but we will have to revert `ENV=production` resulting container is defunct.
